In [1]:
import numpy as np

### Задание 1

In [3]:
a = np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [5]:
mean_a = np.array([np.mean(a[0:5, 0:1]), np.mean(a[:, 1:])])
mean_a

array([2. , 8.4])

### Задание 2

In [6]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 3

In [9]:
a_centered_sp = a_centered_sp = a_centered[0:1, 0:1] * a_centered[0:1, 1:2] + a_centered[1:2, 0:1] * a_centered[1:2, 1:2] + a_centered[2:3, 0:1] * a_centered[2:3, 1:2] + a_centered[3:4, 0:1] * a_centered[3:4, 1:2] + a_centered[4:5, 0:1] * a_centered[4:5, 1:2]
a_centered_sp

array([[8.]])

In [11]:
N = a.shape[0]
N

5

In [13]:
result = a_centered_sp / (N - 1)
result

array([[2.]])

### Задание 4**

In [16]:
a = np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

Транспонируем матрицу a

In [18]:
a.transpose()

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

Вычислим ковариацию траспонированной матрицы

In [22]:
np.cov(a.transpose())

array([[1. , 2. ],
       [2. , 4.3]])

В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации равно элементу в строке с индексом 0 и столбце с индексом 1.