### Задания на повторение пройденного материала

1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [3]:
import numpy as np

In [4]:
a=np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [6]:
a1=a.reshape(3, 4)
a1

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [8]:
a2=a.reshape(4, 3)
a2

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [9]:
a3=a.reshape(2, 6)
a3

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [11]:
a3=a.reshape(6, 2)
a3

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [12]:
a3=a.reshape(12, 1)
a3

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).


In [15]:
b1=a.reshape(6, -1)
b1

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [16]:
b2=a.reshape(4, -1)
b2

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [17]:
b3=a.reshape(3, -1)
b3

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [18]:
b4=a.reshape(-1, 3)
b4

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [20]:
b4=a.reshape(-1, 6)
b4

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?


___Массив из одного столбца - двумерный

In [76]:
a=np.arange(1, 11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
a.shape

(10,)

In [77]:
c=a.reshape(10, 1)
c

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [78]:
c.shape

(10, 1)

Массив имеет количество строк и количество столбцов. 

In [91]:
b1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
b1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [92]:
b2 = np.array([[1], [2], [3], [4], [5], [6], [7], [8], [9], [10]])
b2

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [ ]:
Массив из одного столбца задаётся как двумерный